### ISSUE TITLE
A 404 should be a 404

### ISSUE THREAD

**Issue by pvautour** [Canadian-Geospatial-Platform/geo.ca#100]
Currently, when we should get a 404, we instead redirect the user to the homepage. 

We should instead revert to expected behaviour of returning a 404 for better seo performance.

**Comment by jvanulde** [comment]
@jaredkinger @PVautour I think we should try to get this in the mid-February release.

**Comment by jaredkinger** [comment]
@jvanulde @PVautour Since we deploy the site as static WordPress is no longer in control of handling 404s. I believe this would ultimately be a CloudFront issue. We should be able to create a custom 404 error page and set it in the distribution's Error Pages tab. The current behaviour is odd though as no 404 gets returned and the user is served the HTML from https://geo.ca/index.html. This could be the result of a misconfiguration but I can't say for certain as I don't have access to AWS.

There is a guide for [Generating Custom Error Responses](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/GeneratingCustomErrorResponses.html)

> You can have CloudFront return an object to the viewer (for example, an HTML file) when your Amazon S3 or custom origin returns an HTTP 4xx or 5xx status code to CloudFront. You can also specify how long an error response from your origin or a custom error page is cached in CloudFront edge caches.

[Custom error pages and error caching](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesErrorPages) may also be relevant.

I can however provide the HTML for a proper 404 page though we should be able to test the configuration with a simple HTML file.

**Comment by jvanulde** [comment]
@PVautour, @indiciumx is this something we need @arashmalekz to do?

**Comment by pvautour** [comment]
I'm looking into it now. I found a post on stackexchange claiming this could be related to permalink setting and htaccess.

What i noticed is dev.geo.ca/aaaa.txt has a different behaviour than dev.geo.ca/wordpress/aaaa.txt.

Ill look more into it. But this makes it seem it's not related to our static deploy.

**Comment by jaredkinger** [comment]
@PVautour when we deploy the WordPress instance as a static site there is no .htaccess. The permalink settings won't have an effect on this either. Once it has been generated as static, WordPress is no longer loaded at all and just the generated HTML from the pages is what we are left with.

If you were to try to hit https://wordpress.dev.geo.ca/wordpress/bad-url you can see how WordPress would actually handle a 404. It will return a proper 404 error code.

You will get a blank white screen when you try to access: dev.geo.ca/wordpress/aaaa.txt because the static site was generated with relative URLs and they break on nested 404s. I plan to switch things over to absolute URLs in the next static site generation as it is causing SEO issues too.

**Comment by pvautour** [comment]
Oh ok thanks now i understand the nuance. I didn't know we had a static version in dev xD.

I see the difference now. Ok so Ill wait until you make the switch to absolute urls before looking more into this.

**Comment by jaredkinger** [comment]
The absolute URLs shouldn't have an effect on adding proper 404 handling, they are just affecting the display of current 404s depending on the depth of the URL. The 404 handling needs to be done by Cloudfront.

Currently when a document gets requested that doesn't exist the root index.html page (splash page with language selector) gets served with a 200. Example: https://geo.ca/this-should-404.html

If there requested document is a level deeper than the root and doesn't exist like: https://geo.ca/this-should-404/index.html that's when you get the white screen because it is still trying to serve root index.html which has relative URLs to the assets so everything is just broken.

Both example URLs above should serve a separate custom 404 page and not the root index.html. 

Have a look here: https://catalog.us-east-1.prod.workshops.aws/workshops/9331108e-464e-4699-8a9c-486090105878/en-US/50-configure-custom-error-page

My best guess right now, is that the distributions are set up to serve /index.html on a 404 with a custom 200 response. Instead we should create a custom 404 page and serve a 404 response. If that is the case then we can test on the dev distribution with a really simply 404 page. If that works I will generate the html for a proper 404 page with header. footer etc to be used on production.

**Comment by pvautour** [comment]
@jaredkinger ok thanks i found the setting. Removing it in dev now gives an access denied instead of redirecting.

I just need to set it up to return a 404. Be back with news.

**Comment by pvautour** [comment]
Ok got it fixed for both app.geo.ca and geo.ca. Just need to make shure that the wordpress exports a 404.html to the root of the project when we trigger the static export. app.geo.ca does it now.

**Comment by pvautour** [comment]
@jaredkinger Think you can set us up with a 404.html at the root of the static file exports? For some reason i'm unable to access wp-filemanager.

I can always take care of testing the result of an export to make shure it's bundled in correctly.

**Comment by jaredkinger** [comment]
@PVautour I will generate a 404.html page that matches geo.ca and get it included in the static export tomorrow.

Thanks for taking care of this!

**Comment by pvautour** [comment]
Weirdly enough, setting the cloudfront config to return a 404 page for inexistant pages on app.geo.ca causes valid search query urls to return a 404. 

This for example, returns a 404 even though it loads fine from within the app when you press search: https://app-dev.geo.ca/result?id=b352a71a-011e-4a8e-b97c-77eae5ed3226&lang=en

Cloudfront probably triggers the 404 page based on what it sees in the bucket. If the result page for the specific result is not pre-generated and stored in the bucket it might be why it thinks the page does not exist.

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/100?planning-poker) with Zenhub @PVautour

**Comment by pvautour** [comment]
Done

**Comment by jaredkinger** [comment]
I've come up with a concept for the 404 page that includes both French and English. This concept is based off of the [WET-BOEW template](https://wet-boew.github.io/GCWeb/templates/servermessage/404-en-fr.html) and the [Canada.ca Error Page](https://www.canada.ca/errors/404.html)

You can view it on the dev site here: https://wordpress.dev.geo.ca/wordpress/404/

![404](https://user-images.githubusercontent.com/24461497/217367522-4a69b90f-7ee2-4b6f-b50e-b4286fb0fc7b.jpeg)

@PVautour I'm cleaning up the static version to remove any unnecessary markup/assets and rewrite URLs then I will pass that on to you. Should have it ready first thing tomorrow morning.

**Comment by pvautour** [comment]
Looks good!

**Comment by pvautour** [comment]
A [commit](https://github.com/Canadian-Geospatial-Platform/app.geo.ca/commit/10569dc47da1b729faccdfae356bfa77bb0a8d9c) has been made in app.geo.ca that redirects 404's to `geo.ca/404.html` when it makes it into prod we can close this issue.
