### ISSUE TITLE
Some <img> tags don't have an ALT attribute defined

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geo.ca#105]
Use the `<img alt>` attribute to write descriptive content for the image: `<img source='pic.gif' alt='Accurate and descriptive keyword text that represents the image.' />`.

As a general rule, search engines do not interpret the content of image files. The text provided in the `<img alt>` attribute enables the site owner to provide relevant information to the search engine and to the end user. Alt text is helpful to end users if they have images disabled or if the image does not properly load. In addition, the Alt text is utilized by screen readers. Make sure that your Alt text is descriptive and accurately reflects what the image represents and supports the content on the page.

* [x] https://www.geo.ca/fr/accueil/index.html
* [x] https://www.geo.ca/fr/environnement/index.html
* [x] https://geo.ca/home/index.html
* [x] https://www.geo.ca/fr/galerie-de-cartes/index.html
* [x] https://geo.ca/geo-in-the-news/index.html
* [x] https://geo.ca/
* [x] https://geo.ca/CA/fr/index.html
* [ ] https://datacube.services.geo.ca/en/viewer/elevation/index.html

**Comment by jaredkinger** [comment]
The offending image for all https://geo.ca URLs is the header logo. I've added alt text to the logo when fixing #79 

https://geo.ca/CA/fr/index.html should be a 404 but displays the language selector however the page is broken due to relative URLs.

The offending image on the datacube page is the government of Canada logo: https://datacube.services.geo.ca/gcweb/assets/sig-blk-en.svg
