### ISSUE TITLE
Meta Description tag missing from 182 pages

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geo.ca#106]
The description is missing in the head section of the page. Search engines may use the description provided in the <description> tag in the search engine results page (SERP). A well-written description that pertains to the content of the page and that is relevant to the searcher's intent can help you increase traffic since it can help improve the click-through rate of your page in search.

[geo.ca_PagesByIssueCategory_2022-12-20.pdf](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/10270515/geo.ca_PagesByIssueCategory_2022-12-20.pdf)

**Comment by jvanulde** [comment]
@jaredkinger is this on your radar?

**Comment by jaredkinger** [comment]
@jvanulde The majority of the URLs in document are on https://app.geo.ca. Those meta descriptions should be added as part of my recommendations on #55. The content for the descriptions exists so the tag just needs to be added with the appropriate content on render.

The https://geo.ca URLs listed in the document are all Viewer pages that exist as HTML files within the /wp-content/ directory. None of them have a meta description set so it's a straight forward fix to add the descriptions. These maps appear to be part of the FGP Viewer. Are there documents or data available that would contain descriptions for these maps? If descriptions don't exist then we will need to have them written.

Example Viewer Page: https://geo.ca/wp-content/Viewer/config-int-ENVIRONMENT1-iframe-map-en.html
These Viewer pages are linked to from the theme pages like: https://geo.ca/environment/index.html

On a side note it would be possible to bring these maps into WordPress as a custom post type and manage the page tiles/meta descriptions and some of the other SEO features from within WordPress instead of having to edit HTML files directly. We could also setup a proper page template that still includes the site header/footer while still providing a large screen real estate for the maps. However I have heard mentions that the RAMP viewers were being replaced?

**Comment by elatsis** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/106?planning-poker) with Zenhub @jvanulde @jaredkinger

**Comment by jaredkinger** [comment]
@sean-eagles Please assign this to me. Thanks!

**Comment by jaredkinger** [comment]
All 36 Viewer html pages have been updated with a meta description. In addition to adding the missing meta descriptions I have added canonical tags and alternate link tags for the localized versions of the pages.
