### ISSUE TITLE
SEO review

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#112]
@jaredkinger to review SEO and suggest fixes, add issues where needed.

**Comment by jaredkinger** [comment]
I performed a 60+ point Technical SEO Review/Audit of GEO.ca to find gaps in our technical SEO. During this review I was able to identify 8 issues we can improve upon.

## Technical Issues from Audit

### Pages need a focus keyword
Each page should be targeting a specific keyword or key phrase. No two pages should target the same keyword to avoid keyword cannibalization. Important areas that should include the primary keywords, secondary keywords, or related keywords:

- URL 
- Title tag 
- Meta description 
- H1-H6 tags
- Body text
- Image alt text

### Title tags should be unique and contain the focus keyword or a variation of it
Titles are a ranking factor and one of the main things that searchers user to help determine whether they will click a link. A well-written title can influence users to click through to a page. Titles should be limited to a length of 50-60 characters and include the focus keyword near the beginning if possible.

### Unique meta descriptions should contain keywords
Meta descriptions aren’t used as a ranking factor but can help influence click through rates. Each page should have a unique and compelling meta description that includes the focus keyword in the natural flow of the language. The optimal length of a meta description is between 50-160 characters. Keywords matching a user’s search term will often be bolded helping to encourage users to click through. Google won’t always use the meta description that is provided and will sometimes create its own description from a page’s content. A page may show a different description in the search results based on the user’s search query.

### Content should be keyword focused
Page content should include the keywords and variations of the keywords while maintaining the language's natural flow and readability. It is important to avoid keyword stuffing. High quality content should always be a top priority over optimization.

### Content organized with hierarchical HTML tags
Page content should have a proper logical order of headings to convey the hierarchical structure of a page. In general, this has been done throughout the site but is currently being disrupted by headings in the mega menu.

### Display publication dates/modified date
Displaying the publication date/modified date for a page can help show freshness/relevance in the search results and influence users to click through. A publication date should be added to bottom of each page to achieve this. This would also be inline with other government sites.

### Descriptive filenames for images
Images are often uploaded without renaming the filename to something descriptive of the images. The images will often use the same filename that was provided by the stock photo site they were downloaded from. It would be a time-consuming endeavor to update all the current image filenames and fix the broken links that would result from this. Moving forward images should have descriptive filenames if possible. There may be archiving/copyright restrictions that would prevent us from applying this. This is a very low priority item.

### Sitemap submitted to Search Engines
The sitemap has not been submitted to Bing. Determine if a Bing webmaster tools account already exists or create a new account if needed and submit the sitemap to Bing. 

## Moving Beyond Technical SEO

### Content Strategy
A content strategy should be developed and employed to ensure that we are reaching our target audience and providing appropriate content. Some questions to ask ourselves when developing a content strategy are:

- Who is our audience?
- What are their issues and needs?
- What questions can we answer?
- What content do they want to consume?
- How can we match our data/content to the needs of our audience?

### Keyword Research
Once we have a clearly defined content strategy keyword research should be performed to determine what keywords our audience is using and what questions they are asking. A root keyword can be chosen to then build a keyword theme off of and assist in determining focus keywords for pages.

### Link Building & Establishing Authority
We have a unique opportunity to generate authoritative backlinks from government domains. We may already be doing this, but we should get any related government sites we can link to GEO.ca. This should not be done in a spammy way but should be done in a way that is logical and provides real value to the users of the sites creating a backlink. Consider leveraging funding partners in the same way.

The link text used by sites providing the backlinks is important and should be informative and descriptive of the content that it is linking to. Ideally the link text would contain the focus keyword (or variation of it) of the page being linked to.

### Challenges
There is a lack of search volume for "geospatial data" which could be problematic. A lack of search volume makes discovering secondary or related keywords difficult. It could also mean that users simply aren't searching for what we are delivering. This makes it crucial for us to clearly define who our audience is so that we can learn more about their needs and serve them content in a way that is meaningful to them. Defining our audience needs to go beyond the broad user groups of "General Public", "Curious Public" and "Specialized User".

## Actionable Items

- [x] Add publication/modified date to all pages
- [x] Remove heading tags from mega menu
- [x] Submit sitemap to Bing
- [x] Generate and submit sitemap for https://geo.ca/
- [x] Remove feed (RSS), XMLRPC and REST API links from head tag
- [x] Remove search from schema data
- [x] Include /Viewer/ maps in sitemap
