### ISSUE TITLE
Revised theme - design and implementation

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#120]
@jaredkinger @vgulyy work with each other to design a new revised theme where needed.

**Comment by jaredkinger** [comment]
Creating a custom theme for GEO.CA will allow us to improve the performance (#92), reduce the time needed to build new pages and enforce design consistency site wide. 

Currently the site uses the free Phlox multi-purpose WordPress theme. This theme brings in a large amount of bloat as it has a ton of features that we aren't using. The theme also requires it's own plugin Phlox Core Elements which adds more bloat. The bloat I am referring to is unused scripts and styles that are loaded with every page load. The Phlox theme also adds some CSS that breaks some accessibility features built into the browser. For example keyboard navigation and control focus has been overridden by the Phlox theme and we can restore this to the browser defaults in the new theme.

To further complicate the issue of bloat the vast majority of styles are overridden by Elementor. There has been some misuse of Elementor to achieve the site's current styling by setting typography, colors and other styling on each and every element. This adds additional unnecessary CSS and prevents the site from inheriting styles or leveraging default settings. Using Elementor in this fashion will make it some what tedious to roll out the new styles as I will need to go through each active page and reset the styling for each element so that it can properly inherit it from the styles/default settings. Some elements may need to be reworked as well. Elementor is also an area that needs a bit of cleanup and I will be creating a separate issue for that.

The theme will be based off the stylings from the single page community design (#108). Down the road however it would be in our best interest to have @vgulyy develop a style/brand guide that will outline the typography, colours, iconography, buttons etc. to further refine the design and potentially share the styling among our different teams for a consistent look and feel across subdomains.

**Comment by jaredkinger** [comment]
The Phlox WordPress theme has been replaced with a new custom lightweight theme named "Geo" that supports Elementor. The new theme brings an updated look and feel featuring more consistent typography, colors, buttons and card styling. Additional styling updates will be coming as part of #144.

Switching to the new theme allowed us to drop a lot of bloat and reduce the impact of unused css/javascript. The switch required each page of the site to be updated manually. Elementor styles that were previously being set on each and every element have been reset to allow them to inherit the styling from the theme to reduce page weight and provide consistency across pages. Many pages were not setup to be properly responsive for tablet or large phone sizes that created overflow issues, inconsistent gutters or squished content. These responsive issues were corrected as part of the update.

Previously classes were being set on sections and columns to achieve certain styling. These classes have been removed and the styling has been achieved using a combination of native and custom Elementor widgets. This creates a more user friendly experience for the content editors as they can stick to dragging and dropping widgets without having remember a set of classes. By removing these classes/stlying that were reliant on Elementor's older HTML markup we were able to turn on Elementor's Optimized DOM Output, Improved Asset Loading and Improved CSS loading which provide additional performance boosts for #92.

Further enhancements to the GEO theme will be added as separate issues.
