### ISSUE TITLE
Copyright date incorrect

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geo.ca#121]
In the footer on Geo.ca we have: "Powered by GEO.CA, copyright © 2022"

We should update that to "Powered by GEO.CA, copyright © 2023"

**Comment by jvanulde** [comment]
@jaredkinger please action. @Andrea-Merry FYI.

**Comment by bo-lu** [comment]
@jvanulde Do you mean 2023?

**Comment by jaredkinger** [comment]
Footer copyright year updated to 2023 for both French and English footers. This is up on https://wordpress.dev.geo.ca

I took this a step further and made this dynamic via a shortcode that will return the current year. This is run on the server side so it would require a static site deployment but this should help prevent this from being a yearly update.

Glad this got raised though because the dev site was still referencing CGP here "Powered by the Canadian Geospatial Platform, copyright © 2023" so I have updated that to reflect what is on production. 

The French copyright text on production  reads "Propulsé par GEO.CA, **copyright** © 2022" should that read "Propulsé par GEO.CA, **droits d’auteur** © 2023"?

**Comment by jvanulde** [comment]
> Footer copyright year updated to 2023 for both French and English footers. This is up on https://wordpress.dev.geo.ca
> 
> I took this a step further and made this dynamic via a shortcode that will return the current year. This is run on the server side so it would require a static site deployment but this should help prevent this from being a yearly update.
> 
> Glad this got raised though because the dev site was still referencing CGP here "Powered by the Canadian Geospatial Platform, copyright © 2023" so I have updated that to reflect what is on production.
> 
> The French copyright text on production reads "Propulsé par GEO.CA, **copyright** © 2022" should that read "Propulsé par GEO.CA, **droits d’auteur** © 2023"?

@Andrea-Merry can you confirm French translation please.

**Comment by Andrea-Merry** [comment]
After speaking to a few francophones, the translation is:
Propulsé par GEO.CA, droits d’auteur © 2023
