### ISSUE TITLE
Contact Us Page on GEO.ca

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#186]
@jaredkinger @sean-eagles  @heamart Hi. The content team wants to remove the Contact Us page(s) in EN and FR on GEO.ca. 
https://geo.ca/contact/
https://geo.ca/fr/contactez-nous/

Instead it makes more sense to have the contact us information with the email address in the footer. 
Thank you,
Andrea

**Comment by jaredkinger** [comment]
@Andrea-Merry We can setup a mailto link in the footer. With mailto links you can prefill the subject line, is that something your team would be interested in doing?

**Comment by sean-eagles** [comment]
@Andrea-Merry @heamart we can definitely look into getting this done, is Jared's solution of a mailto link in the footer sufficient?   @jaredkinger you have been assigned.

**Comment by heamart** [comment]
Yes, definitely will need a mailto link. Here are the details of what we kinda want to do. 
- add the contact information in the new footer on the right side ( next to "discover by organization"). If we could put the following text:

**Contact Us**
Canada Centre for Mapping and Earth Observation
Natural Resources Canada
Government of Canada
[geo@nrcan-rncan.gc.ca](mailto:geo@nrcan-rncan.gc.ca)

Also, since we are removing the contact-us page there are a few links throughout the site that go to that page. These can be updated to a mailto link as well if possible. It's on the Contributors, Getting Started, and About Us pages in the  Questions?Comments?Ideas? sections.

Lastly, in the part of the footer at the bottom (with the link to the terms of reference and another contact us link), the contact us could be updated to a mailto link or removed completely - if you have an opinion one way or the other on that link feel free to do either.

Let us know when it's in dev, we'll have to get approvals since we are explicitly listing the organization name. It's just make it easier to actually show it "in action"

**Comment by jaredkinger** [comment]
@Andrea-Merry @heamart I've updated the all of the links to the contact page to mailto links. The footer has been updated to include the contact information provided. I did however change the position of the contact information. Placing it to the right of the "Discover by Organization" would be outside of the page container and adjusting the current columns to 5 from 4 would squish a lot of the links. I tried below the "Discover by Organization" links but that gave it a cluttered look. I ended up placing it in the bottom left below the footer navigation. 

Have a look on dev here: https://wordpress.dev.geo.ca/home/ and let me know if that works for you. Thanks!

**Comment by Andrea-Merry** [comment]
@jaredkinger @heamart Thank you Jared. Looks good to us. Please proceed with implementation.

**Comment by Andrea-Merry** [comment]
@jaredkinger Hi. I checked on EN and FR and the contact us pages are still discoverable. Will they be archived?
The footer is completed.
https://geo.ca/contact/
https://geo.ca/fr/contactez-nous/

**Comment by jaredkinger** [comment]
@Andrea-Merry The EN/FR contact pages should have been redirected but unfortunately the update for that got missed as it is separate from the static generation. I am working with Bo to find out what we need to do policy/procedure wise to push that change now that we are outside of the release window. I will update as soon as I have more information.
