### ISSUE TITLE
GEO News page update

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#196]
To show smaller releases, links to publications, articles etc.

Currently just the one page, but will continue to add items to it as released or requested by content owner, so hopefully adding multi-page function is the future is possible - probably want to show max 6 or 9 per page

Items will include: thumbnail, publication date, description.

Mock up, there are some comments in the file:
[geoNewsMockup3Comments.pdf](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/12050879/geoNewsMockup3Comments.pdf)

- Archive Discover the Value of GEO page due to no clear purpose (have added the content on this page the GEO News page)
-  On GEO News remove the RSS feed (not inclusive enough of the rest of CCMEO)

**Comment by heamart** [comment]
and the translations

[Actualites de GEO_DRAFT_FR.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/12085040/Actualites.de.GEO_DRAFT_FR.docx)

**Comment by jaredkinger** [comment]
I've updated the news page here on dev: https://wordpress.dev.geo.ca/geo-in-the-news/

Should we be adding a news item for [COVID-19](https://geo.ca/geo-in-the-news/covid-19/)? It's currently featured on the [news page](https://geo.ca/geo-in-the-news) and I don't believe it is linked to anywhere else on the site.

Another thing to note is that I'd like to change the URL for https://geo.ca/discover-value-geo/recognizing-women-with-canadian-place-names/ to https://geo.ca/geo-in-the-news/recognizing-women-with-canadian-place-names/ since we are archiving the Discover the Value of GEO page.

**Comment by heamart** [comment]
Thank you, it looks great. 
Yes, please add the Covid-19. It will be with the date April 29, 2021
and go ahead with the URL changes.

**Comment by jaredkinger** [comment]
COVID-19 has been added to the news page, the URL for Recognizing Women with Canadian Place Names has been updated and the Discover the Value of GEO page has been archived.

**Comment by jaredkinger** [comment]
There was a typo on the French page LiDAR card title: "Nouveau produit Nuages de **poins** LiDAR" this has been updated to "Nouveau produit Nuages de **points** LiDAR"
