### ISSUE TITLE
Permafrost community theme pages

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#399]
@jaredkinger @jennywilsonsewell @heamart 
Good morning Jared,
We finally have some mock-ups ready for DEV in GEO.ca for the Permafrost community. 
Please add a card for the [Permafrost Community](https://geo.ca/communities/permafrost) under [Community Profiles](https://geo.ca/communities/ ) with this text:
The Permafrost Community is a central hub for permafrost information in Canada. Featuring data and tools from three provinces and two territories.
The first page is the [Permafrost main page](https://geo.ca/communities/permafrost) which will include the interactive map as we discussed the last time we met. I know you said you wanted to make it more modular than what it currently is for FHIMP. Also, would it be possible to grey out the P/Ts on the map that are not contributors that we do not have resources available at this point? The links for the images are in the word document except for the banner image which is attached. The list of resources by Provinces and Territories for the interactive map are in the attached zip file.
![BannerImagePermafrost](https://github.com/user-attachments/assets/190d258f-bb78-46fb-a11c-fd1a124eca24)

The second page is the [Permafrost by Province page](https://geo.ca/communities/permafrost/permafrost-by-province) which is linked to from the main page.
The third page is the [Permafrost by Territory page](https://geo.ca/communities/permafrost/permafrost-by-territory) which is also linked to from the main page.
Please let me know if you have any questions. Once in DEV we will share the links with our partners and Allison for approval before getting it translated and implemented in PROD.
Thank you! We are really excited to finally have a new community in GEO.ca.
Andrea
[Permafrost Theme V2.zip](https://github.com/user-attachments/files/16378982/Permafrost.Theme.V2.zip)

**Comment by jaredkinger** [comment]
Hi Andrea,

I've added the permafrost pages to dev. You can view them at the links below:

- [Permafrost](https://wordpress.dev.geo.ca/communities/permafrost/)
- [Permafrost by Province](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-province/)
- [Permafrost by Territory](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-territory/)

Please have a look through the pages and send me your feedback.

For the interactive map I've set the colours to purples as opposed to the greenish colour used by FHIMP. For the P/Ts that don't have any resources I've disabled clicks and hover actions and hidden the labels so that users aren't able to interact with them. The dropdown only lists the P/Ts with content. 

I've also added a card to the [Communities](https://wordpress.dev.geo.ca/communities/) page for Permafrost.

There was placeholder text for the Province and Territory cards below the interactive map on the main Permafrost page so I just used the description from each of those pages. If these descriptions should be something else please let me know.

It wasn't clear to me what the attributions for the images on the Province and Territory pages should be so I've just used a placeholder for the time being. Are you able to provide me with the attributes for each image?

Thanks!

**Comment by Andrea-Merry** [comment]
Hi Jared,
The pages look great! I will get Jenny to provide you with the attributes for each image. Is it possible to have the Permafrost community card first on the page since it is the most recent?
Thank you,
Andrea

**Comment by jaredkinger** [comment]
@Andrea-Merry I shifted the cards on the [Communities](https://wordpress.dev.geo.ca/communities/) page to put the Permafrost Community first.

**Comment by jennywilsonsewell** [comment]
@jaredkinger The pages are looking great!

For the [Community](https://wordpress.dev.geo.ca/communities/) and [Permafrost](https://wordpress.dev.geo.ca/communities/permafrost/) pages, can we please update the title descriptions from:
"A central hub for permafrost information in Canada. Featuring data and tools from three provinces and two territories."

to:
"A central hub for permafrost information in Canada. Featuring data and tools from contributing provinces and territories."

Can we also please update the [Permafrost by Province](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-province/) and [Permafrost by Territory](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-territory/) card and title descriptions from:
"Permafrost data and tools from three of Canada’s provinces." and
"Permafrost data and tools from two of Canada’s territories."

to:
"Discover the implications of permafrost across contributing provinces in Canada.”  and
“Discover the implications of permafrost across contributing territories in Canada.”

I will send you the finalized attributions for the map images ASAP. 

Thank you,
Jenny

**Comment by jennywilsonsewell** [comment]
Hi @jaredkinger, @heamart, @Andrea-Merry 

The attributions for the map images on the [Permafrost by Province](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-province/) and [Permafrost by Territory](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-territory/) are listed below. If you could please add each to the caption of the corresponding image, that would be great:


**AB:**
Pawley, S.M. and Utting, D.J. “Identifying Permafrost in Northern Alberta” [Image], Alberta Energy Regulator, AER/AGS Digital Data, 2018. [[https://ags.aer.ca/research-initiatives/permafrost](https://ags.aer.ca/research-initiatives/permafrost)], (accessed July 2nd, 2024). Licensed under the [Open Government Licence – Alberta](https://open.alberta.ca/licence).

**MB:**
Priscilla Addison. “Location of the HBR from The Pas to Churchill showing the varying permafrost conditions” [Image], ResearchGate, 2016. [[https://www.researchgate.net/publication/303901766_Embankment_Stabilization_Techniques_for_Railroads_on_Permafrost](https://www.researchgate.net/publication/303901766_Embankment_Stabilization_Techniques_for_Railroads_on_Permafrost)], (accessed July 2nd, 2024). Licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).

**QC:**
Ministry Of Natural Resources and Forests. “Permafrost in Nunavik” [Dataset], in Données Québec, 2021, updated August 31st, 2023. [[https://www.donneesquebec.ca/recherche/dataset/pergelisol-au-nunavik](https://www.donneesquebec.ca/recherche/dataset/pergelisol-au-nunavik) (French only)], (accessed July 2nd, 2024). Licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).

**NWT:**
Steve Kokelj. “Slump-affected terrain in northwestern Canada and positions of the Laurentide Ice Sheet from ca. 18–11 ka” [Image], Northwest Territories Geological Survey, Government of Northwest Territories, 2017. [[https://www.nwtgeoscience.ca/sites/ntgs/files/resources/geology-2017-kokelj-g38626.1.pdf](https://www.nwtgeoscience.ca/sites/ntgs/files/resources/geology-2017-kokelj-g38626.1.pdf)], (accessed July 2nd, 2024). Licensed under [CC-BY](https://creativecommons.org/licenses/by/2.0/deed.en).

**YK:**
Daniel Fortier. “Map showing permafrost-affected area on North Alaska Highway” [Image], ResearchGate, 2009. [[https://www.researchgate.net/publication/268815619_Cost_and_Constructability_of_Permafrost_Test_Sections_Along_the_Alaska_Highway_Yukon](https://www.researchgate.net/publication/268815619_Cost_and_Constructability_of_Permafrost_Test_Sections_Along_the_Alaska_Highway_Yukon)], (accessed July 2nd, 2024). Licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).

Thank you,
Jenny

**Comment by jaredkinger** [comment]
@jennywilsonsewell I've updated the [Province page](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-province/) and the [Territory page](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-territory/) with the attributions.

Also just confirming that the text changes requested previously were completed. Please review the changes and let me know if I missed anything. Thanks!

**Comment by jennywilsonsewell** [comment]
@jaredkinger @heamart @Andrea-Merry  
Hey Jared,
Can we please make the following changes, based on the feedback we received from our YK contributor:

On the [Permafrost](https://wordpress.dev.geo.ca/communities/permafrost/) page, can we update the following text:

"Permafrost is soil or rock that remains at or below 0°C for at least two years. Approximately 50% of Canada has permafrost beneath the surface, measuring at more than 700 meters in thickness in the High Arctic. It is an important piece of the northern Canadian landscape."

**to**

"Permafrost is soil or rock that remains at or below 0°C for at least two years. Approximately 50% of Canada has permafrost beneath the surface, ranging from a few metres thick in the subarctic to several hundred metres thick in the high arctic. It is an important piece of the northern Canadian landscape."

Can we also add a _Related Sites_ section at the bottom of the page, to include the following external links and descriptions:

1. [Permafrost Map - 6th edition (The Atlas of Canada)](https://natural-resources.canada.ca/maps-tools-and-publications/maps/atlas-canada/land-and-water/26099#details-panelGeomorphology2)
"This map shows different levels of permafrost occurrence across Canada."

2. [Permafrost 101 (Canadian Permafrost Association)](https://canadianpermafrostassociation.ca/What-is-Permafrost.htm)
"Permafrost is present where the climate is cold but the surface is not covered by glaciers.  It is found across the North and at high elevations in mountainous areas such as the Rocky Mountains in western Canada and the Chic-Choc Mountains in the East."

On the [Permafrost by Territory](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-territory/) page, can we update the following text:

1. "Mitigating Degradation in the Southwest" **to** "Mitigating Degradation to the Alaska Highway"

**and**

2. "Near Whitehorse and the Alaska Highway, a thaw slump, or permafrost landslide, eroded a further 13 metres just in the summer of 2023. The damage is so close to Whitehorse and the highway that the [Yukon government is building a new section of road](https://yukon.ca/en/alaska-highway-safety-improvements) further from the river, to ensure public safety and protect the only year-round road linking parts of the Yukon and Alaska to the rest of the continent. Researchers at [Yukon University](https://www.yukonu.ca/research/research-centre/permafrost-geoscience) are working with the government to come up with a plan to mitigate concerns for the long-term feasibility of the road."

**to**

"Near Whitehorse, a permafrost thaw slump has been growing closer to the Alaska Highway since 2014 at rates up to 19 m per year. In 2023, the highway was rerouted about 80 m back from the landslide to mitigate concerns that the landslide might damage the road. Researchers at [Yukon University](https://www.yukonu.ca/) are working with [Yukon Government](https://yukon.ca/) to monitor the site, ensure public safety, and protect the only year-round road linking parts of the Yukon and Alaska to the rest of the continent."

Thank you,
Jenny

**Comment by jennywilsonsewell** [comment]
@jaredkinger @heamart @Andrea-Merry 

Some more changes from YK:

On the [Permafrost](https://wordpress.dev.geo.ca/communities/permafrost/) page, can we please edit the list of Yukon's resources in the interactive map so that the [Yukon Permafrost Database](https://service.yukon.ca/permafrost/) link appears first in the list.

Please also change to the "GEO.ca" links under each list of resources for each AB, MB, NT, QC, and YK to say "GEO.ca Datasets".

Lastly, please change the image under Yukon to the following (sizing ideally to match the other P/T images):
![MAX_1581_2022_Sept_20](https://github.com/user-attachments/assets/cb5c02d4-3a26-46bb-b29a-5b665c154c63)

With the updated attribution: [Yukon Geological Survey](https://data.geology.gov.yk.ca/)

Thanks again,
Jenny

**Comment by jaredkinger** [comment]
@jennywilsonsewell I've made the requested updates in the last two comments to the [Permafrost](https://wordpress.dev.geo.ca/communities/permafrost/) page and the [Permafrost by Territory](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-territory/) page. 

Please review and let me know if further changes are required. Thanks!

**Comment by jennywilsonsewell** [comment]
@jaredkinger

Looking great! Thanks for getting these updates done so quickly. 

The only changes required are:

1. Please change the attributions to have no italics. This was recommended by Web Publishing "to match the most consistent web style." (Canada.ca)
2. For the YK image, please add the caption "Thaw slumps along the Alaska Highway in 2022", before the attribution, and update the attribution to say "Credit: [Yukon Geological Survey](https://data.geology.gov.yk.ca/)"

Cheers,
Jenny

**Comment by jaredkinger** [comment]
@jennywilsonsewell I've removed the italics in the captions from both [Province](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-province/) and [Territory](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-territory/) pages. The Yukon caption/attribution has been updated.

**Comment by jennywilsonsewell** [comment]
@jaredkinger @Andrea-Merry 

On the [Permafrost page](https://wordpress.dev.geo.ca/communities/permafrost/), please update the text above the dropdown menu for the interactive map **from** 
"Select a province/territory" **to** 
"Select a province or territory to display provincial/territorial resources." to match the Flood Mapping in your Province or Territory page.

Thank you,
Jenny

**Comment by jaredkinger** [comment]
@jennywilsonsewell I added the "Select a province or territory to display provincial/territorial resources." text above the map and flipped the dropdown label to "Province or Territory" to match the Flood Mapping Province or Territory page. I want to keep the label short and concise so we don't get it wrapping to two lines. Let me know if that works for you.

**Comment by jennywilsonsewell** [comment]
@jaredkinger 

Perfect, thank you. If we could make the "Province or Territory" label a 22px h4 to match the  Flood Mapping in your Province or Territory page, that would be ideal, but if it doesn't work or make sense, not to worry. 

You rock,
Jenny

**Comment by jaredkinger** [comment]
@jennywilsonsewell I've adjusted the font size for the label to match the Flood Mapping in your Province or Territory page.

**Comment by jennywilsonsewell** [comment]
@jaredkinger @Andrea-Merry 

1. We've decided to change the images on the [Permafrost by Province](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-province/) and [Permafrost by Territory](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-territory/) pages to photos that are more true to the GEO.ca look and feel, as well as to match the YK photo. Please update the images, captions, and attributions for the following P/Ts (please size the photos to be similar to one another, if possible):

**AB:**
![Angel_glacier_and_a_rock_rabbit_enjoying_the_view _50891599841_50_small](https://github.com/user-attachments/assets/a80df8b4-40a3-40bf-861e-b0062baa6baf)
Rock glaciers in alpine environments indicate permafrost conditions in Jasper, Alberta. “[Angel glacier and a rock rabbit enjoying the view.](https://www.flickr.com/photos/bernd_thaller/50891599841/)” by [Bernd Thaller](https://www.flickr.com/people/44296132@N06) is licensed under [CC-BY-2.0](https://creativecommons.org/licenses/by/2.0/deed.en).

**MB:** 
![End_of_the_line,_Churchill_Manitoba_(30352378547)](https://github.com/user-attachments/assets/c6d1edaf-23dd-401f-9465-3d0ee95a7600)
The Hudson Bay Rail Line has been the only mode of transport to Churchill, Manitoba since 1929. “[end of the line, Churchill Manitoba](https://www.flickr.com/photos/31856336@N03/30352378547/)” by [Mike Beauregard](https://www.flickr.com/people/31856336@N03) is licensed under [CC-BY-2.0](https://creativecommons.org/licenses/by/2.0/deed.en).

**QC:**
![Pano_Salluit](https://github.com/user-attachments/assets/db2b5df9-57d2-4eeb-a76b-046dd09b60d7)
Thawing permafrost can lead to shifts in the ground and damage to units in Nunavik, Quebec. “[Pano Salluit](https://upload.wikimedia.org/wikipedia/commons/7/76/Pano_Salluit.JPG)” by [Diane Frappier](https://commons.wikimedia.org/wiki/File:Pano_Salluit.JPG#:~:text=Author-,Diane%20Frappier,-Other%20versions) is licensed under [CC-BY-3.0](https://creativecommons.org/licenses/by/3.0/deed.en).

**NWT:**
![arcticsummer63](https://github.com/user-attachments/assets/cdb06194-0434-4bc5-add9-689d30eb893a)
A thaw slump consists of a headwall made predominately of ice and a floor of saturated silt and clay. “[Thaw Slump - geohazard](https://www.nwtgeoscience.ca/file/thaw-slump-geohazard)” by [Brendan O'Neill](https://www.researchgate.net/profile/H-Brendan-Oneill) contains information licensed under the [Open Government License Northwest Territories](https://www.gov.nt.ca/en/open-government-licence-northwest-territories).

2. Lastly, on the main [Permafrost page](https://wordpress.dev.geo.ca/communities/permafrost/), please update the text on the purple card (under the dropdown menu) to include "Permafrost Resources" after the P/T name. E.g., "Alberta Permafrost Resources"

Thank you, and my apologies for all the small changes over these last weeks.

**Comment by jaredkinger** [comment]
@jennywilsonsewell I've updated the cards on the [Permafrost](https://wordpress.dev.geo.ca/communities/permafrost/) page and updated the images on the [Province](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-province/) and [Territory](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-territory/) pages. I was able to crop and resize the images to make them all a consistent size.

**Comment by jennywilsonsewell** [comment]
@jaredkinger 

Thank you. I just noticed the Quebec caption/attribution didn't get changed over, but everything else is great.

**Comment by jaredkinger** [comment]
@jennywilsonsewell Good catch. I've gone ahead and updated this for Quebec.

**Comment by jennywilsonsewell** [comment]
@jaredkinger @Andrea-Merry 

Hi Jared,
Here is the translated content for the French pages:
[041-240927-002_DD_ENG_FRA.zip](https://github.com/user-attachments/files/17262754/041-240927-002_DD_ENG_FRA.zip)

I believe the "Additional Text" document is meant to be alt text for the stock banner images. I'm not sure they're needed though, as they are decorative images. 

Thank you!

**Comment by jaredkinger** [comment]
@jennywilsonsewell For the main page is there translations for the [interactive map content](https://wordpress.dev.geo.ca/fr/communautes/pergelisol/#alberta)? 

On the French [Province](https://wordpress.dev.geo.ca/fr/communautes/pergelisol/le-pergelisol-par-province/) and [Territory](https://wordpress.dev.geo.ca/fr/communautes/pergelisol/le-pergelisol-par-territoire/) pages do we need to add "(en anglais seulement)" to sites pointing to English only pages like [Northwest Territories Geological Survey](https://www.nwtgeoscience.ca/). Would this also apply to links in the photo captions?

**Comment by jennywilsonsewell** [comment]
@jaredkinger 

1. Attached is the French text for the [interactive map content](https://wordpress.dev.geo.ca/fr/communautes/pergelisol/#alberta)

[FR_permafrost_resources.docx](https://github.com/user-attachments/files/17413140/FR_permafrost_resources.docx)

2. On the [English page](https://wordpress.dev.geo.ca/communities/permafrost/), please update the Quebec links **from:**

- [GEO.ca Datasets](https://app.geo.ca/?keyword=permafrost&org=government%20and%20municipalities%20of%20qu%C3%A9bec)
- [ArcGIS – Permafrost Data](https://experience.arcgis.com/experience/9d16b16f8b664a2b82ee10a5486d4e84/page/home/?draft=true&views=view_1)
- [Laval University](https://www.ulaval.ca/la-recherche/unites-de-recherche/chaires-de-recherche-en-partenariat/chaire-de-recherche-en-partenariat-sur-le-pergelisol-au-nunavik)
- [Open Data Quebec](https://www.donneesquebec.ca/recherche/dataset?organization=&q=Perg%C3%A9lisol)

**to:**

- [GEO.ca Datasets](https://app.geo.ca/?keyword=permafrost&org=government%20and%20municipalities%20of%20qu%C3%A9bec) 
- [Permafrost Research Laboratory, Université Laval](https://experience.arcgis.com/experience/9d16b16f8b664a2b82ee10a5486d4e84/page/home/?draft=true&views=view_1) 
- [L'Université Laval (French only)](https://www.ulaval.ca/la-recherche/unites-de-recherche/chaires-de-recherche-en-partenariat/chaire-de-recherche-en-partenariat-sur-le-pergelisol-au-nunavik) 
- [Partenariat Données Québec (French only)](https://www.donneesquebec.ca/recherche/dataset?organization=&q=Perg%C3%A9lisol)

3. At this point, I believe it would be best practice to have all English or French only links specify that the content is only available in either language, including the photo captions. The only links that can be excluded from that practice would be the actual photo links, since they link to images rather than text content (e.g., "[Angel glacier and a rock rabbit enjoying the view.](https://www.flickr.com/photos/bernd_thaller/50891599841/)"). I will share any updates on this with you as I learn more.

4. Please update the MB photo and attribution to the following (caption can remain). If this updated photo allows for the others to be enlarged to line up better with the text content, that would be great:

![churchill_IMG_0292-scaled-1601973335](https://github.com/user-attachments/assets/2fc70e0f-f709-4502-a69b-f57fa3e1f548)
Credit: [Paradox](https://paradoxaccess.com/). 
Mention de la source : [Paradox](https://paradoxaccess.com/).

Thank you,
Jenny

**Comment by jaredkinger** [comment]
Hi @jennywilsonsewell,

1. The content for the [interactive map](https://wordpress.dev.geo.ca/fr/communautes/pergelisol/#alberta) has been updated with the French translations
2. The resource links for [Quebec](https://wordpress.dev.geo.ca/communities/permafrost/#quebec) on the English page are updated
3. For the French [Province](https://wordpress.dev.geo.ca/fr/communautes/pergelisol/le-pergelisol-par-province/) and [Territory](https://wordpress.dev.geo.ca/fr/communautes/pergelisol/le-pergelisol-par-territoire/) pages I added (en anglais seulement) to links where applicable
4. The Manitoba image is updated and I've enlarged the size of the photos and left-aligned them on the [Province](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-province/) and [Territory](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-territory/) pages to match what were doing for Critical Minerals.

Have a look through the updates and let me know if I missed anything. Thanks!

**Comment by jennywilsonsewell** [comment]
@jaredkinger 

It looks great! Just two small changes:

On the [English](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-province/) and [French](https://wordpress.dev.geo.ca/fr/communautes/pergelisol/le-pergelisol-par-province/) Provincial pages, can you please add MB's photo caption back in front of the attribution:
Since 1929, the Hudson Bay Rail Line has been the only mode of transport to Churchill, Manitoba. / 
Depuis 1929, la ligne ferroviaire de la baie d'Hudson est le seul moyen de transport pour se rendre à Churchill, Manitoba.

and

On the English [Territory page](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-territory/) in the NWT attribution, please link [Brendan O'Neill](https://www.researchgate.net/profile/H-Brendan-Oneill).

Thank you,
Jenny

**Comment by jaredkinger** [comment]
@jennywilsonsewell 

[English](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-province/) and [French](https://wordpress.dev.geo.ca/fr/communautes/pergelisol/le-pergelisol-par-province/) Provincial pages are updated with the caption back for Manitoba. Sorry I missed that note about leaving it there.

The attribution on the English [Territory page](https://wordpress.dev.geo.ca/communities/permafrost/permafrost-by-territory/) is updated with a link to [Brendan O'Neill](https://www.researchgate.net/profile/H-Brendan-Oneill).
