### ISSUE TITLE
User Story: Popularity and date filters

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geo.ca#63]
As a user, I would like to have the site rank the content based on popularity, so that I may determine what geospatial resources are most important to Canadians.

**Comment by jvanulde** [comment]
@SebastienDurand: thumbnails be a should have

**Comment by SebastienDurand** [comment]
Honestly visuals are key, it must be something visual


De : Joost van Ulden ***@***.***>
Envoyé : novembre 2, 2022 15:29
À : Canadian-Geospatial-Platform/geo.ca ***@***.***>
Cc : Sébastien Durand ***@***.***>; Mention ***@***.***>
Objet : Re: [Canadian-Geospatial-Platform/geo.ca] User Story: Popularity (Issue #63)

***Caution - email originated from outside of NRCan. Read the warning below / Attention- Ce courriel provient de l'extérieur des RNCan. Voir la mise en garde ci-dessous***


@SebastienDurand<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSebastienDurand&data=05%7C01%7Csebastien.durand%40NRCan-RNCan.gc.ca%7Cbb355f6f798441c3631808dabd088328%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638030141512263771%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LrgZnRvCi2VKwhxPeg2lmYaXr0bUEbaAu0cAhW2oJcE%3D&reserved=0>: thumbnails be a should have

-
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCanadian-Geospatial-Platform%2Fgeo.ca%2Fissues%2F63%23issuecomment-1301113378&data=05%7C01%7Csebastien.durand%40NRCan-RNCan.gc.ca%7Cbb355f6f798441c3631808dabd088328%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638030141512263771%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PyNPh0N%2B1vp3HtE1Adg79k6yyb1HEfLsGCGRQaEPo6I%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAM3J6TPX6ZFESJSQXF726YDWGK6HRANCNFSM6AAAAAARPK5OOM&data=05%7C01%7Csebastien.durand%40NRCan-RNCan.gc.ca%7Cbb355f6f798441c3631808dabd088328%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638030141512263771%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TOnwFy57gh%2FYzDkS9t700XJScgnD40MFsGQbz4hsi84%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>
This email originated from outside of NRCan. Do not click links or open attachments unless you recognize the sender and believe the content is safe. For more information, please visit How to Identify Phishing<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fintranet.nrcan.gc.ca%2Fservices-policies%2Fdont-get-scammed-cyber-security-101&data=05%7C01%7Csebastien.durand%40NRCan-RNCan.gc.ca%7Cbb355f6f798441c3631808dabd088328%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638030141512263771%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=y7JT%2BE76raPEimW1LvltJ4%2F2MG6vtQJYjnVYoQrQ1fA%3D&reserved=0> emails on the NRCan Intranet.
Ce courriel provient de l'extérieur des RNCan. Ne cliquez pas sur les liens et n'ouvrez pas les pièces jointes, à moins de connaître l'expéditeur et croire que le contenu est sécuritaire. Pour de plus amples renseignements, veuillez consulter Comment identifier des courriels d'hameçonnages<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fintranet.nrcan.gc.ca%2Fservices-policies%2Fdont-get-scammed-cyber-security-101&data=05%7C01%7Csebastien.durand%40NRCan-RNCan.gc.ca%7Cbb355f6f798441c3631808dabd088328%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638030141512263771%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=y7JT%2BE76raPEimW1LvltJ4%2F2MG6vtQJYjnVYoQrQ1fA%3D&reserved=0> dans l'intranet des RNCan.

**Comment by elatsis** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/63?planning-poker) with Zenhub @bo-lu @dennisfu @jvanulde @sean-eagles @xinli-cai

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/63?planning-poker) with Zenhub @SebastienDurand

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/63?planning-poker) with Zenhub @indiciumx

**Comment by ehfounder** [comment]
Not sure if we planned on this for this sprint or when it should be done.

**Comment by jvanulde** [comment]
@indiciumx this is targeted for release in mid-February. @bo-lu has this been deployed yet to DEV?

**Comment by bo-lu** [comment]
Sort by date published has a bug where many records do not have a date published (Not Available), so sorting descending is producing erroneous results.

Popularity is working on dev to extract popularity from gcgeo records and I am working to finalize the code to summarize analytics from the geo.ca dynamodb table.

**Comment by bo-lu** [comment]
Released on app-dev.geo.ca Feb 21, 2023

**Comment by bo-lu** [comment]
Hi John @johnweng001 ,

When the filter is provided in the url, can it automatically be selected on the interface?

E.g., https://app-dev.geo.ca/?keyword_only=&theme=&lang=en&foundational=&type=&keyword=wildfire&sort=popularity-desc

This should select the 'Popularity *downarrow*' on the dropdown.

**Comment by johnweng001** [comment]
Hi Bo, yes and PR created. 
(also I found that keyword_only param has a bug, it should also take user to keyword only page when keyword_only=true is provided in the url.  I can fix it as well. ) @bo-lu

**Comment by bo-lu** [comment]
Thanks, accepted [PR-31](https://github.com/Canadian-Geospatial-Platform/app.geo.ca/pull/31) and merged into dev.

**Comment by bo-lu** [comment]
It is working well in app-dev.geo.ca with behaviour detailed below:

Keyword only search (keyword_only=true) will load the keyword only search UI and filter by popularity in descending order (sort=popularity-desc):
https://app-dev.geo.ca/?keyword_only=true&theme=&lang=en&foundational=&type=&keyword=earthquake&sort=popularity-desc

Spatial search (keyword_only=false or null) will load the spatial search UI and filter by date in descending order (sort=date-desc)
https://app-dev.geo.ca/?keyword_only=false&theme=&lang=en&foundational=&type=&keyword=earthquake&sort=date-desc

**Comment by bo-lu** [comment]
The popularity and date filters are ready to go.
For posterity, this was accomplished by:
- [x] Create a DynamoDB table called analytics_popularity with uuid as HASH and popularity as RANGE
- [x] Creating popularity lambda function which assigns a popularity value to the analytics_popularity table based on the geo.ca analytics DynamoDB table and the GeoNetwork popularity for tie-breaking and seeding the popularity. Currently the 'mixing' formula is to multiple the geo.ca popularity by 10 000 and adding the GeoNetwork popularity. Future released may remove the GeoNetwork popularity tie-breaking mechanism easily. Multiprocessing was added for performance.
- [x] Updated the geocore-to-parquet lambda to query the popularity and append the value to the parquet file. Also fixes an issue where the publication date may be Not Available. See: https://github.com/Canadian-Geospatial-Platform/geocore_to_parquet/commit/4f2e8b6410a04520bd0af74c00c8d131797afcbe
