### ISSUE TITLE
wordpress.dev.geo.ca URI resolves to Apache test page

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geo.ca#94]
The wordpress.dev.geo.ca URI should resolve to https://wordpress.dev.geo.ca/wordpress/

**Comment by jaredkinger** [comment]
It is possible to have WordPress installed in it's own directory and remove /wordpress/ from the frontend URLs. Accessing the admin would still be located at https://wordpress.dev.geo.ca/wordpress/wp-admin/ and uploads and plugin/theme assets would still be located in their respective directories under at https://wordpress.dev.geo.ca/wordpress/wp-content/.

Alternatively WordPress could be installed into the root directory and we could get rid of /wordpress/ altogether from all URLs. This would be my recommendation unless there is a specific reason to have WordPress installed in it's own directory.

Both of these options would correct this issue without a redirect. Not a necessity but something to think about.

**Comment by jaredkinger** [comment]
@indiciumx has confirmed that having WordPress in it's own subfolder was not done by necessity. I will explore moving WordPress to the root and rewriting the URLs in the database to provide a smooth transition.

**Comment by jaredkinger** [comment]
I've moved the WordPress install out of the /wordpress/ sub directory and into the root. I did a find and replace on the database to update all of the URLs. The .htacess was also updated to use the root as the rewrite base and updated the index.php rewrite rules. Simply Static Pro and Elementor Pro licenses have been migrated to the new URL. 

The install now loads when you access https://wordpress.dev.geo.ca instead of the apache test page. I've added a wildcard redirect to redirect all old https://wordpress.dev.geo.ca/wordpress URLs to https://wordpress.dev.geo.ca.

This issue resolves #145 for https://wordpress.dev.geo.ca

@sean-eagles This issue can be closed.
